eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://43.204.33.207:8761/eureka/,http://65.2.61.113:8761/eureka/
  instance:
    hostname: 43.204.33.207
